/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedResumoRouteImport } from './routes/_authenticated/resumo'
import { Route as AuthenticatedNovaRouteImport } from './routes/_authenticated/nova'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedEditarIdRouteImport } from './routes/_authenticated/editar.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumoRoute = AuthenticatedResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaRoute = AuthenticatedNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditarIdRoute = AuthenticatedEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/conta': typeof AuthenticatedContaRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/resumo': typeof AuthenticatedResumoRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/conta': typeof AuthenticatedContaRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/resumo': typeof AuthenticatedResumoRoute
  '/': typeof AuthenticatedIndexRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/nova': typeof AuthenticatedNovaRoute
  '/_authenticated/resumo': typeof AuthenticatedResumoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/editar/$id': typeof AuthenticatedEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/conta' | '/nova' | '/resumo' | '/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/conta' | '/nova' | '/resumo' | '/' | '/editar/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/conta'
    | '/_authenticated/nova'
    | '/_authenticated/resumo'
    | '/_authenticated/'
    | '/_authenticated/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumo': {
      id: '/_authenticated/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof AuthenticatedResumoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova': {
      id: '/_authenticated/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AuthenticatedNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editar/$id': {
      id: '/_authenticated/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof AuthenticatedEditarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedNovaRoute: typeof AuthenticatedNovaRoute
  AuthenticatedResumoRoute: typeof AuthenticatedResumoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEditarIdRoute: typeof AuthenticatedEditarIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedNovaRoute: AuthenticatedNovaRoute,
  AuthenticatedResumoRoute: AuthenticatedResumoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEditarIdRoute: AuthenticatedEditarIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
